language: python
matrix:
  include:
    - python: "2.7"
      sudo: false
    - python: "3.5"
      sudo: false
    - python: "3.6"
      sudo: false
    - python: "3.7"
      dist: xenial
      sudo: true
install:
    - pip install -U setuptools zc.buildout
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
