language: python
sudo: false
dist: bionic
cache: pip
matrix:
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
install:
    - pip install -r requirements.txt
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
